### PR TITLE
Fix request encoding precision

### LINKED ISSUE #17: Precision issue
```
λ> B.postEncode $ B.OrderRequest B.XRPXBT B.BID 673 0.00002683
[("pair","XRPXBT"),("type","BID"),("volume","673"),("price","0.000026")]
```
Not sure where we're losing precision but this is clearly wrong!

### PR DESCRIPTION
**Pull request by mithrandi**
Fixes #17 

@tebello-thejane are you okay with this approach?

### CODE REVIEW

**Comment by tebello-thejane** [comment]
Checking it out.

**Comment by tebello-thejane** [comment]
> . toRational $ **truncate6** k

This must have been failing for `ETH`, as well? Damn...

**Comment by tebello-thejane** [comment]
Yeah. I think the `Data.ByteString.Builder.Scientific` approach looks good. That's what I was trying to do with `showFFloat`, as well as the smelly `truncate6`. 

Thanks! :-D

**Comment by mithrandi** [comment]
The XRP books are the first to allow more than 4 decimals, weirdly!

**Comment by tebello-thejane** [comment]
So, Luno must be returning only 4 decimals for all other books, then. But for some strange reason they used better precision for `XRP`? 

YOLO.

**Comment by mithrandi** [comment]
The updated doctests cover it, but I could add to the hspec tests if you like?

**Comment by tebello-thejane** [comment]
The doctests, it would appear, were wrong, since they forced 6 decimal precision. Thanks for the update. 

Looks perfect. :-D

**Pull request merged**
